[package]
name = "minior"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { version = "1.0.3", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.5.0"
tokio = { version = "1.35.0", features = [] }

[dev-dependencies]
reqwest = "0.11.23"
uuid = { version = "1.6.1", features = ["v4"] }
tokio = { version = "1.35.0", features = ["full"] }
